{% set version = "2.14.2" %}

package:
  name: git
  version: {{ version }}

source:
  fn: git-{{ version }}.tar.gz                                                                                                    # [unix]
  url: https://github.com/git/git/archive/v{{ version }}.tar.gz                                                                   # [unix]
  sha256: 917bbb401b20cabb65ffcaf925064e1990b2337bb20219c2963f1768ff33162b                                                        # [unix]
  fn: PortableGit-{{ version }}-32-bit.7z.exe                                                                                     # [win32]
  url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-32-bit.7z.exe  # [win32]
  sha256: 6acd886bb1cebee7b5b607599c8327453110c28ddd8c4f976d14050ab0a17e11                                                        # [win32]
  fn: PortableGit-{{ version }}-64-bit.7z.exe                                                                                     # [win64]
  url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-64-bit.7z.exe  # [win64]
  sha256: 3d451383519379dfe2f160c4c3a49e4b9e39a666698f3eea2534593cc3fb5a4e                                                        # [win64]

build:
  number: 2
  skip: true  # [win and not py27]
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: true

requirements:
  build:
    - autoconf        # [unix]
    - curl >=7.44.0,<8  # [unix]
    - expat           # [unix]
    - libiconv 1.15        # [unix]
    - openssl 1.0.*   # [unix]
    - zlib 1.2.11      # [unix]
    - 7za             # [win]

    # Workaround for conda-build issue.
    - python          # [win]
  run:
    - curl >=7.44.0,<8  # [unix]
    - expat           # [unix]
    - libiconv 1.15        # [unix]
    - openssl 1.0.*   # [unix]
    - zlib 1.2.11      # [unix]

test:
  commands:
    # Verify git location.
    - test -f $PREFIX/bin/git                               # [unix]
    - if not exist %LIBRARY_PREFIX%\\bin\\git.exe exit 1    # [win]

    # Run git commands.
    - git --version
    - git clone https://github.com/conda-forge/git-feedstock

    # test completions
    - bash $PREFIX/share/bash-completion/completions/git  # [unix]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://git-scm.com/
  license: GPL v2 and LGPL 2.1
  summary: distributed version control system

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - scopatz
    - ocefpaf
