{% set version = "2.55.0" %}

package:
  name: git
  version: {{ version }}

source:
  - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-{{ version }}.tar.gz  # [not win]
    folder: code  # [not win]
    sha256: 0842dc384a23ac33ba3e570c4f3a8ded85963ee4713b1cd21153c3db41813d1e  # [not win]
    patches:   # [not win]
      - 0001-macOS-Do-not-use-the-system-Wish-urgh.patch  # [not win]
  - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-manpages-{{ version }}.tar.gz  # [not win]
    folder: manpages  # [not win]
    sha256: e1d56c160c55be805d339613d6c5cdb1269d5346a50d757c39135f1449e28ed5  # [not win]
  - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-htmldocs-{{ version }}.tar.gz  # [not win]
    folder: htmldocs  # [not win]
    sha256: 8cc302f07f4d246b556c4f4f57cdc0aa7f13a57f9b5c94629ff8ec26cddf66b5  # [not win]

  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-64-bit.7z.exe  # [win64]
    folder: .  # [win64]
    sha256: dfa8cad3ce7e685b9bfbbb2125afcf7c68d4f53490426702ffac367dac62e928  # [win64]

build:
  number: 2
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - perl 5.*  # [unix]

requirements:
  build:
    - {{ stdlib('c') }}    # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('rust') }}  # [unix]
    - {{ stdlib("c") }}    # [unix]
    - autoconf  # [unix]
    - make      # [unix]
    - 7za       # [win]
    - tk        # [unix]
    - gettext-tools   # [unix]
  host:
    - libintl-devel  # [osx]
    - libcurl        # [unix]
    - expat          # [unix]
    - libiconv       # [unix]
    - openssl        # [unix]
    - pcre2          # [unix]
    - perl 5.*       # [unix]
    - zlib           # [unix]
  run:
    # Without the explicit dependency on curl, it seems
    # that linux_64 fails on the symbol lookup for curl_global_sslset
    - perl 5.*  # [unix]

test:
  commands:
    # Verify git location.
    - test -f $PREFIX/bin/git                               # [unix]
    - test -f $PREFIX/bin/gitk                              # [unix]
    - test -f $PREFIX/bin/git-credential-osxkeychain        # [osx]
    - if not exist %LIBRARY_PREFIX%\\bin\\git.exe exit 1    # [win]

    # Run git commands.
    - git --version
    - git clone https://github.com/conda-forge/git-feedstock

    # Git credential commands
    - git-credential-osxkeychain 2>&1 | grep -q usage  # [osx]

    # test completions
    - bash $PREFIX/share/bash-completion/completions/git  # [unix]

    # test subtree presence
    - test -f $PREFIX/libexec/git-core/git-subtree  # [unix]

    # confirm toplevel manpage
    - test -f $PREFIX/man/man1/git.1  # [not win]
    - test -f $PREFIX/share/man/man1/git.1  # [osx]

    # confirm toplevel html doc page
    - test -f $PREFIX/share/doc/git/index.html  # [not win]

about:
  home: https://git-scm.com/
  license: GPL-2.0-or-later and LGPL-2.1-or-later
  license_file: code/COPYING  # [not win]
  summary: distributed version control system

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - scopatz
    - ocefpaf
    - djsutherland
    - ytausch
