{% set version = "2.14.3" %}

package:
  name: git
  version: {{ version }}

source:
  fn: git-{{ version }}.tar.gz                                                                                                    # [unix]
  url: https://github.com/git/git/archive/v{{ version }}.tar.gz                                                                   # [unix]
  sha256: 2b1d952078795117a8c4549f6384275e047ebd75c10bea77e675f8b672e6d87a
  fn: PortableGit-{{ version }}-32-bit.7z.exe                                                                                     # [win32]
  url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-32-bit.7z.exe  # [win32]
  sha256: 2b1d952078795117a8c4549f6384275e047ebd75c10bea77e675f8b672e6d87a
  fn: PortableGit-{{ version }}-64-bit.7z.exe                                                                                     # [win64]
  url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-64-bit.7z.exe  # [win64]
  sha256: 2b1d952078795117a8c4549f6384275e047ebd75c10bea77e675f8b672e6d87a

build:
  number: 0
  skip: true  # [win and not py27]
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: true

requirements:
  build:
    - autoconf        # [unix]
    - curl >=7.44.0,<8  # [unix]
    - expat 2.2.*           # [unix]
    - libiconv 1.15        # [unix]
    - openssl 1.0.*   # [unix]
    - zlib 1.2.11      # [unix]
    - 7za             # [win]

    # Workaround for conda-build issue.
    - python          # [win]
  run:
    - curl >=7.44.0,<8  # [unix]
    - expat 2.2.*           # [unix]
    - libiconv 1.15        # [unix]
    - openssl 1.0.*   # [unix]
    - zlib 1.2.11      # [unix]

test:
  commands:
    # Verify git location.
    - test -f $PREFIX/bin/git                               # [unix]
    - if not exist %LIBRARY_PREFIX%\\bin\\git.exe exit 1    # [win]

    # Run git commands.
    - git --version
    - git clone https://github.com/conda-forge/git-feedstock

    # test completions
    - bash $PREFIX/share/bash-completion/completions/git  # [unix]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://git-scm.com/
  license: GPL v2 and LGPL 2.1
  summary: distributed version control system

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - scopatz
    - ocefpaf
