{% set version = "2.8.1" %}

package:
  name: git
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz                                                                                                       # [unix]
  url: https://github.com/git/git/archive/v{{ version }}.tar.gz                                                                   # [unix]
  sha256: 8d53703d75890c03e26a915c7af3b7b98d8cfb94382f685a9bcbee1eeaec47b4                                                        # [unix]

build:
  number:   0
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: true

requirements:
  build:
    - curl      # [unix]
    - expat     # [unix]
    - openssl   # [unix]
    - zlib      # [unix]
  run:
    - expat     # [unix]
    - certifi   # [unix]
    - curl      # [unix]
    - openssl   # [unix]
    - zlib      # [unix]
    - m2-base   # [win]
    - m2-git  {{ version }}  # [win]

test:
  commands:
    - git --version

about:
  home: https://git-scm.com/
  license: GPL v2 and LGPL 2.1
  summary: distributed version control system

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
